name: Code Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '18'

jobs:
  # Code quality check only (deployment handled by Vercel)
  quality-check:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: project/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./project
        run: npm ci

      - name: Run linter (non-blocking)
        working-directory: ./project
        run: npm run lint || echo "⚠️ Linting issues found"

      - name: Build check
        working-directory: ./project
        run: npm run build

      - name: Security audit (non-blocking)
        working-directory: ./project
        run: npm audit --audit-level=high || echo "⚠️ Security vulnerabilities found"

  # Success notification
  quality-passed:
    name: Quality Check Passed
    runs-on: ubuntu-latest
    needs: [quality-check]
    if: success()
    
    steps:
      - name: Quality passed notification
        run: |
          echo "✅ Code quality checks passed! Vercel will handle deployment automatically."